# Generated by Django 3.1.4 on 2021-01-04 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_auto_20210104_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsmodel',
            name='finish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lmsmodel',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lmsmodel',
            name='memo',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='lmsmodel',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
