# Generated by Django 3.1.4 on 2021-01-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_auto_20210104_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmsmodel',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lmsmodel',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
