# Generated by Django 3.1.4 on 2021-01-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_auto_20210104_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmsmodel',
            name='date',
            field=models.DateField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='lmsmodel',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
