# Generated by Django 3.1.4 on 2021-01-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_auto_20210104_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmsmodel',
            name='time',
            field=models.DateTimeField(default='', null=True),
        ),
    ]
