# Generated by Django 3.1.4 on 2021-01-07 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_auto_20210104_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmsmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='lmsmodel',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
