# Generated by Django 3.1.4 on 2021-01-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_auto_20210107_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmsmodel',
            name='goal',
            field=models.IntegerField(choices=[(1, '1 hour/day'), (2, '2 hours/day'), (3, '3 hours/day'), (4, '4 hours/day'), (5, '5 hours/day'), (6, '6 hours/day'), (7, '7 hours/day'), (8, '8 hours/day')], null=True),
        ),
    ]
