# Generated by Django 3.1.4 on 2021-01-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_lmsmodel_goal'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.IntegerField(choices=[(1, '1 hour/day'), (2, '2 hours/day'), (3, '3 hours/day'), (4, '4 hours/day'), (5, '5 hours/day'), (6, '6 hours/day'), (7, '7 hours/day'), (8, '8 hours/day')], null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='lmsmodel',
            name='goal',
        ),
    ]
